import type { Metadata } from "next";
import { Geist, Geist_Mono, Monoton } from "next/font/google";
import Script from "next/script";
import TerminalLoader from "@/components/TerminalLoader";
import ParticleBackground from "@/components/ParticleBackground";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const brandDisplay = Monoton({
  variable: "--font-brand-display",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeBootstrapScript = `
  try {
    var savedTheme = localStorage.getItem("w4whiskers-page-theme");
    document.documentElement.dataset.theme = savedTheme === "light" ? "light" : "dark";
  } catch (error) {
    document.documentElement.dataset.theme = "dark";
  }
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${brandDisplay.variable} relative min-h-screen isolate antialiased`}
      >
        <Script id="theme-bootstrap" strategy="beforeInteractive">
          {themeBootstrapScript}
        </Script>
        <div className="fixed inset-0 z-0">
          <ParticleBackground />
        </div>
        <TerminalLoader />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
